name: "CPU Build with composite action"

on:
  pull_request:
    branches:
      - main
      - upstream
      - 'dist-ndarray'
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'intel-innersource/frameworks.ai.mlir.mlir-extensions'
    runs-on: cpu1
    timeout-minutes: 450

    env:
      HOME: /home/gta/actions-runner/_work/frameworks.ai.mlir.mlir-extensions/frameworks.ai.mlir.mlir-extensions/build_cpu_v2/home

    steps:
      - name: Clear home dir
        run: |
          mkdir -p $HOME
          cd $HOME
          rm -rf *

      - uses: actions/checkout@v3
        with:
          token: ${{secrets.WORKFLOW_TOKEN}}
          path: ${{env.HOME_DIR}}/frameworks.ai.mlir.mlir-extensions
      - uses: ./frameworks,ai.mlir.mlir-extensions/.github/workflows/build-cpu-composite-action
