name: "CPU Build with composite action"

on:
  pull_request:
    branches:
      - main
      - upstream
      - 'dist-ndarray'
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'intel-innersource/frameworks.ai.mlir.mlir-extensions'
    runs-on: cpu1
    timeout-minutes: 450

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/build-cpu-composite-action
