# Sync innersouce repo to upstream mlir-extensions

name: Sync to Upstream Public Repo

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-main:
  ###
  # Syncs main branch of this repo to open source intel/mlir-extensions
  ###
    runs-on: gpu

    env:
      BUILD_ROOT: /home/gta/actions-runner/_work/frameworks.ai.mlir.mlir-extensions/frameworks.ai.mlir.mlir-extensions/sync
      HOME_DIR: /home/gta/actions-runner/_work/frameworks.ai.mlir.mlir-extensions/frameworks.ai.mlir.mlir-extensions/sync/home

    steps:
      - name: Check build root
        run: |
          if [ ! -d "$BUILD_ROOT" ]; then mkdir -p $BUILD_ROOT; fi

      - name: Clear home dir
        run: |
          mkdir -p $HOME_DIR
          cd $HOME_DIR
          rm -rf *

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          ref: main
          fetch-depth: 0
          path: ${{env.HOME_DIR}}/frameworks.ai.mlir.mlir-extensions
      - name: Remove Upstream
        run: |
          if git remote | grep upstream; then
            git remote remove upstream
          else
            echo "upstream does not exist"
          fi
      - name: Add Upstream
        run: git remote add upstream https://github.com/intel/mlir-extensions.git
      - name: Fetch Upstream
        run: git fetch upstream
      - name: Merge Upstream with git merge
        run: git merge upstream/main --no-edit
      - name: Push
        run: |
          git push -f origin main
