# Sync innersouce repo to upstream mlir-extensions

name: Sync to Upstream Public Repo

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:

jobs:
  sync-main:
  ###
  # Syncs main branch of this repo to open source intel/mlir-extensions
  ###
    runs-on: [self-hosted, pvc, glados]

    steps:
      - name: Check build root
        run: |
          export BUILD_ROOT=$(pwd)/sync
          echo BUILD_ROOT=${BUILD_ROOT} >> $GITHUB_ENV
          export HOME_DIR=${BUILD_ROOT}/home
          echo HOME_DIR=${HOME_DIR} >> $GITHUB_ENV
          if [ ! -d "$BUILD_ROOT" ]; then mkdir -p $BUILD_ROOT; fi

      - name: Clear home dir
        run: |
          mkdir -p $HOME_DIR
          cd $HOME_DIR
          rm -rf *

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          ref: main
          fetch-depth: 0
          path: ${{env.HOME_DIR}}/frameworks.ai.mlir.mlir-extensions
      - name: Remove Upstream
        run: |
          cd $HOME_DIR/frameworks.ai.mlir.mlir-extensions
          if git remote | grep upstream; then
            git remote remove upstream
          else
            echo "upstream does not exist"
          fi
      - name: Add Upstream
        run: |
          cd $HOME_DIR/frameworks.ai.mlir.mlir-extensions
          git remote add upstream https://github.com/intel/mlir-extensions.git
      - name: Fetch Upstream
        run: |
          cd $HOME_DIR/frameworks.ai.mlir.mlir-extensions
          git fetch upstream
      - name: Merge Upstream with git merge
        run: |
          cd $HOME_DIR/frameworks.ai.mlir.mlir-extensions
          git config --global user.email "alexei.fedotov@gmail.com"
          git config --global user.name "Alexei Fedotov"
          git merge upstream/main --no-edit
      - name: Push
        run: |
          cd $HOME_DIR/frameworks.ai.mlir.mlir-extensions
          git push -f origin main
