name: testing Nightly CI
on:
  workflow_dispatch:
  # add input for email address
    inputs:
      email:
        description: 'Email address to send report to'
        required: true
        default: 'dimpalben.r.prajapati@intel.com'
  schedule:
#   - cron: '0 0 * * *' # every 24 hrs
    - cron: '30 19 * * *' # runs every day at 19:30 pm UTC which is 11:30 am PST
jobs:
  invoke-sync:
    runs-on: gpu
    steps:
      - name: Retrieve version
        run: |
          echo "TAG_NAME=$(pwd)" >> $GITHUB_OUTPUT
      - name: Invoke Sync
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Sync to Upstream Public Repo
          token: ${{secrets.IMEX_GHA_TOKEN}}
